export type Json = Record<string, unknown>;
export type ProjectRole = "owner" | "researcher" | "reviewer";
export type PaperIngestion = { content_availability: "full_text" | "abstract_only"; ingestion_status: "succeeded" | "unavailable" | "failed"; full_text_source: "pdf" | "pmc_xml" | "html" | null; full_text_url: string | null; full_text_chunks: number; ingestion_warning: string | null };
export type Paper = { paper_id: string; title: string; authors: string[]; year: number | null; doi?: string | null; url: string; abstract?: string; cited_by_count: number; is_open_access?: boolean; pdf_url?: string | null; relevance_score?: number | null; rank?: number | null; source?: string; ingestion?: PaperIngestion | null };
export type Project = { project_id: string; name: string; description: string; project_role: ProjectRole; active_report_version_id?: string | null; updated_at: string };
export type Review = { conversation_id?: string | null; project_id: string; job_id: string; topic: string; status: string; requested_by?: string; requested_by_name?: string; created_at: string; report_version_id?: string | null; version_number?: number | null; review_type?: "self_review" | "external_review"; workflow_type?: "litreview" | "research_gap" };
export type Assignment = { assignment_id: string; project_id: string; job_id: string; project_name: string; topic: string; requested_by: string; status: "assigned" | "submitted" | "revoked"; review_status: string; report_version_id?: string | null; version_number?: number | null; review_created_at: string };
export type Version = { report_version_id: string; job_id?: string | null; version_number: number; change_reason: string; created_at: string; report?: Report };
export type EvidenceQuote = { paper_id: string; quote: string; section?: string; source_level?: "full_text" | "abstract" | "snippet"; document_id?: string; start_char?: number; end_char?: number; retrieval_score?: number; context_before?: string; context_after?: string };
export type Claim = { claim_id: string; claim_type?: string; text: string; supporting_paper_ids?: string[]; evidence: EvidenceQuote[]; validation_status?: string; validation_errors?: string[]; evidence_confidence?: "high" | "low"; requires_human_review?: boolean; evidence_verdict?: "supported" | "partial" | "unsupported" | "uncertain" };
export type Reference = { paper_id: string; title: string; authors?: string[]; year?: number | null; doi?: string | null; url: string; metadata_valid?: boolean };
export type Theme = { theme_id: string; title: string; summary_claim_id?: string; supporting_paper_ids?: string[] };
export type PotentialGap = {
  gap_id: string;
  claim_id?: string;
  aspect: string;
  papers_checked?: number;
  scope_statement?: string;
  gap_type?: "topical" | "method" | "contradiction" | "evaluation";
  confidence?: "low" | "medium" | "high";
  counter_search_query?: string;
  reviewer_rationale?: string;
  verification_status?: "grounded" | "needs_counter_search" | "reviewed";
  evidence_score?: number;
  novelty_score?: number;
  feasibility_score?: number;
  quality_score?: number;
  suggested_method?: string;
  falsification_condition?: string;
  source_type?: "author_stated" | "corpus_inferred";
  coverage?: Array<{ paper_id: string; mentioned: boolean; evidence_quote?: string | null }>;
};
export type TraceEvent = { trace_id?: string; decision_id?: string; node: string; summary?: string; action?: string; reason?: string; created_at: string; papers_found?: number };
export type AITraceEvent = { id: string; job_id: string; trace_id: string; node_name: string; provider: string; model: string; event_type: string; attempt: number; status: string; tokens_prompt?: number | null; tokens_completion?: number | null; latency_ms?: number | null; error_type?: string | null; error_message?: string | null; created_at: string };
export type JobTrace = { job_id: string; lifecycle_events: AITraceEvent[]; llm_events: AITraceEvent[]; total_events: number };
export type LiteratureReview = { title: string; abstract: string; introduction: string; sections: Array<{ title: string; paragraphs: string[]; supporting_paper_ids: string[] }>; conclusion: string; limitations: string };
export type Report = { papers?: Paper[]; claims: Claim[]; references: Reference[]; evidence_rows?: Array<{ paper_id: string; citation_label?: string; title?: string; year?: number | null; url?: string }>; scope_disclaimer?: string; narrative?: string; literature_review?: LiteratureReview | null; themes?: Theme[]; potential_gaps?: PotentialGap[]; decision_trace?: TraceEvent[]; source_warnings?: string[]; validation_warnings?: string[]; response_language?: "Vietnamese" | "English" };
export type ReviewResult = Report & { job_id: string; status: string; topic: string; original_topic?: string; intent?: "litreview" | "research_gap" | "out_of_scope" | "unsafe"; assistant_response?: string; response_language?: "Vietnamese" | "English"; search_query?: string; query_history?: string[]; papers_count: number; revision_log?: Array<{ revision_id: string; claim_id: string; action: string; reason: string; revised_text: string; previous_text: string }>; search_attempt?: number; grounding_revision_attempt?: number; review_revision_attempt?: number; review_summary?: { total_claims: number; reviewed_claims: number; supported_claims: number; unsupported_claims: number }; review?: { report_decision: "approve" | "request_changes"; report_note: string; reviewed_at: string } | null };
export type JobStatus = { job_id: string; status: string; current_node: string; papers_found: number; valid_claims: number; search_attempt: number; grounding_revision_attempt: number; review_revision_attempt: number; search_query: string | null; query_history: string[]; sub_queries: string[]; selected_paper_ids: string[]; hitl_stage: "subqueries" | "papers" | "review" | null; execution_mode?: "review" | "autonomous"; last_decision: { action: string; reason: string } | null; warnings: string[]; node_trace: TraceEvent[]; papers: Array<Pick<Paper, "paper_id" | "title" | "authors" | "year" | "url" | "cited_by_count" | "relevance_score" | "source" | "ingestion">>; error: string | null };
export type Invitation = { invitation_id: string; project_id: string; job_id: string; email: string; status: "pending" | "accepted" | "declined" | "expired" | "revoked"; email_delivery_status: "not_configured" | "sent" | "failed"; email_attempts: number };
export type Citation = { citation_id?: string; paper_id?: string; quote: string; source_url?: string };
export type Message = { message_id: string; client_message_id?: string | null; role: "user" | "assistant"; message_type: string; text: string; citations: Citation[]; context_artifact_ids?: string[]; annotations?: string[] };
export type Conversation = { conversation_id: string; title?: string; active_report_version_id?: string | null };
export type ResearchPlan = { plan_id: string; normalized_question: string; sub_queries: string[]; sources: string[]; selection_criteria: string[]; status: string; conversation_id?: string | null };
export type GapStatus = "candidate" | "pending_review" | "supported_in_searched_corpus" | "partially_supported" | "contradicted" | "reviewer_approved" | "reviewer_narrowed" | "reviewer_rejected" | "insufficient_coverage" | "insufficient_evidence";
export type Gap = { gap_id: string; scoped_statement: string; status: GapStatus; report_version_id: string; corpus_size?: number; present_count?: number; not_reported_count?: number; unknown_count?: number; coverage?: Array<{ paper_id: string; mentioned: boolean; evidence_quote?: string | null }>; counterevidence_paper_ids?: string[]; confidence?: "low" | "medium" | "high" | null; counter_search_query?: string | null; reviewer_rationale?: string | null; verification_status?: string | null; evidence_score?: number | null; novelty_score?: number | null; feasibility_score?: number | null; quality_score?: number | null; suggested_method?: string | null; falsification_condition?: string | null; source_type?: "author_stated" | "corpus_inferred" | null };
export type Memory = { memory_id: string; scope: "session" | "project"; memory_type: string; content: Json; status: "proposed" | "active" | "superseded" | "expired" | "deleted" | string; created_at: string; confirmed_by?: string | null; supersedes_memory_id?: string | null };
export type ActionProposal = { action_id: string; action_type: string; reason: string; status: string; base_report_version_id?: string | null; estimated_impact: { summary?: string }; };
export type ReviewFeedback = { feedback_id: string; project_id: string; report_version_id: string; target_type: string; target_id: string; verdict: string; note: string; revised_text?: string | null; requested_action?: string; created_at: string };
export type ProjectMember = { project_id: string; actor_id: string; project_role: ProjectRole; display_name?: string | null; actor_type?: string | null; created_at: string };
